name: Bug Report
description: 反馈一个bug
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        感谢您花时间填写这份 bug 报告！
        
  - type: input
    id: version
    attributes:
      label: 版本号
      description: 您正在使用的版本是什么？
      placeholder: 例如：v1.0.0
    validations:
      required: true
      
  - type: textarea
    id: what-happened
    attributes:
      label: 发生了什么？
      description: 请详细描述遇到的问题
      placeholder: 请详细描述问题...
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: 期望的结果
      description: 请描述您期望看到的结果
    validations:
      required: true
