name: Documentation Issue
description: 报告文档相关的问题或建议（如文档错误、缺失、改进建议等）
title: "[Docs]: "
labels: ["docs"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        感谢您帮助我们改进[文档](https://sjtdev.github.io/koishi-plugin-dota2tracker/)！请填写以下信息来帮助我们更好地理解和解决文档相关的问题。

  - type: dropdown
    id: issue-type
    attributes:
      label: 问题类型
      description: 这是什么类型的文档问题？
      options:
        - 文档错误（错别字、格式问题等）
        - 内容不准确或过时
        - 文档缺失
        - 文档不清晰或难以理解
        - 文档改进建议
        - 其他
    validations:
      required: true

  - type: textarea
    id: current-problem
    attributes:
      label: 当前问题
      description: 请描述您发现的文档问题
      placeholder: |
        例如：
        - 在XX页面中的YY部分存在错别字
        - ZZ功能的使用说明不够清晰
        - 缺少XX功能的安装说明
    validations:
      required: true

  - type: textarea
    id: suggested-changes
    attributes:
      label: 建议的修改
      description: 如果您有具体的修改建议，请在这里详细说明
      placeholder: |
        例如：
        - 将"XXX"改为"YYY"
        - 建议添加以下内容：...
        - 建议重组该部分结构为：...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 补充信息
      description: 还有什么其他信息可以帮助我们理解和解决这个文档问题？
      placeholder: 添加任何有助于理解问题的额外上下文信息...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: 确认
      description: 提交前请确认以下事项
      options:
        - label: 我已经搜索过现有的 issues，确认这不是重复的问题
          required: true
        - label: 我已经仔细检查了问题描述，确保信息准确完整
          required: true
