name: Deploy VitePress site to Pages

on:
  push:
    branches: [master]
    paths:
      - "src/docs/**"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgbm1 \
            libasound2t64 \
            libatk1.0-0 \
            libc6 \
            libcairo2 \
            libcups2 \
            libdbus-1-3 \
            libexpat1 \
            libfontconfig1 \
            libgcc1 \
            libglib2.0-0 \
            libgtk-3-0 \
            libnspr4 \
            libpango-1.0-0 \
            libpangocairo-1.0-0 \
            libstdc++6 \
            libx11-6 \
            libx11-xcb1 \
            libxcb1 \
            libxcomposite1 \
            libxcursor1 \
            libxdamage1 \
            libxext6 \
            libxfixes3 \
            libxi6 \
            libxrandr2 \
            libxrender1 \
            libxss1 \
            libxtst6 \
            ca-certificates \
            fonts-liberation \
            libnss3 \
            lsb-release \
            xdg-utils \
            wget

      - name: Install Maple Mono fonts
        run: |
          # 安装基础英文字体（OTF）
          wget -q https://github.com/subframe7536/maple-font/releases/download/v7.0-beta34/MapleMono-OTF.zip
          unzip -q MapleMono-OTF.zip
          
          sudo mkdir -p /usr/share/fonts/opentype/maple-mono
          
          # 移动所有 OTF 文件
          sudo mv MapleMono-OTF/*.otf /usr/share/fonts/opentype/maple-mono/
          
          # 安装中文支持（使用 OTF）
          wget -q https://github.com/subframe7536/maple-font/releases/download/v7.0-beta34/MapleMono-CN.zip
          unzip -q MapleMono-CN.zip
          
          # 仅移动 OTF 文件（如果存在）
          if [ -f MapleMono-CN/*.otf ]; then
            sudo mv MapleMono-CN/*.otf /usr/share/fonts/opentype/maple-mono/
          else
            echo "Warning: No OTF files found in MapleMono-CN. Using TTF files instead."
            sudo mv MapleMono-CN/*.ttf /usr/share/fonts/opentype/maple-mono/
          fi
          
          # 更新字体缓存
          sudo fc-cache -f -v
          
          # 检查安装的字体
          echo "Installed fonts:"
          fc-list | grep -i "maple"
        shell: /usr/bin/bash -e {0}
        env:
          GITHUB_PAGES: true

      - name: Install dependencies
        run: |
          npm install -D typescript @types/node @types/puppeteer @types/ejs @types/js-yaml @types/i18next
          npm install -D tsx puppeteer ejs vitepress@1.5.0
          npm install dotaconstants moment i18next js-yaml
          npm install @cordisjs/vitepress
          npm install

      - name: Generate Preview Images
        run: |
          npx tsx scripts/generation.ts

      - name: Build Docs
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          npx vitepress build src/docs --debug 2>&1 || { echo "Build failed with error $?"; exit 1; }

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: src/docs/.vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
