name: Deploy VitePress site to Pages

on:
  push:
    branches: [main]
    paths:
      - 'src/docs/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgbm1 \
            libasound2t64 \
            libatk1.0-0 \
            libc6 \
            libcairo2 \
            libcups2 \
            libdbus-1-3 \
            libexpat1 \
            libfontconfig1 \
            libgcc1 \
            libglib2.0-0 \
            libgtk-3-0 \
            libnspr4 \
            libpango-1.0-0 \
            libpangocairo-1.0-0 \
            libstdc++6 \
            libx11-6 \
            libx11-xcb1 \
            libxcb1 \
            libxcomposite1 \
            libxcursor1 \
            libxdamage1 \
            libxext6 \
            libxfixes3 \
            libxi6 \
            libxrandr2 \
            libxrender1 \
            libxss1 \
            libxtst6 \
            ca-certificates \
            fonts-liberation \
            libnss3 \
            lsb-release \
            xdg-utils \
            wget
      
      - name: Install dependencies
        run: |
          npm install -D typescript @types/node @types/puppeteer @types/ejs @types/js-yaml @types/i18next
          npm install -D tsx puppeteer ejs vitepress@1.5.0
          npm install dotaconstants moment i18next js-yaml
          npm install
      
      - name: Generate Preview Images
        run: |
          npx tsx scripts/generation.ts
      
      - name: Check Environment
        run: |
          pwd
          ls -la
          node --version
          npm --version
          echo "Content of src/docs directory:"
          ls -la src/docs

      - name: Verify Config Files
        run: |
          if [ -f "src/docs/.vitepress/config.ts" ]; then
            echo "VitePress config found"
            cat src/docs/.vitepress/config.mts
          else
            echo "VitePress config not found!"
            exit 1
          fi

      - name: Build Docs
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          npx vitepress build src/docs --debug 2>&1 || { echo "Build failed with error $?"; exit 1; }
    
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: src/docs/.vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
